spring.datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: "jdbc:mariadb://49.50.162.195:3306/NETFLIX?characterEncoding=UTF-8&serverTimezone=KST"
    username: netflix
    password: 123\

spring.jpa:
  database: mysql
  database-platform: org.hibernate.dialect.MariaDB10Dialect
  show-sql: true
  hibernate.ddl-auto: update

spring.jpa.properties.hibernate.format_sql: true